# Project-wide Gradle settings.

# Specifies the JVM arguments used for the daemon process.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# AndroidX package structure to make it clearer which packages are bundled
# with the Android operating system, and which are packaged with your
# app's APK. This is required for the project's AndroidX dependencies.
android.useAndroidX=true

# Enables namespacing of each library's R class so that its R class includes
# only the resources declared in the library itself.
android.nonTransitiveRClass=true

# Kotlin code style for this project.
kotlin.code.style=official
